### PR TITLE
fix: use chain properties to get proper balance formatting

### LINKED ISSUE #62: feat: Get chain metadata for unit conversion
Currently we have a hardcoded function for planckToDot that assumes 1 DOT = 1^10 plancks. This is not always the case, see [this table](https://wiki.polkadot.network/learn/learn-dot/#polkadot). We can get around this by simple requesting the units and the decimals from the chain with `api.rpc.system.properties()` so we always have the right unit and decimals.

### PR DESCRIPTION
**Pull request by jmg-duarte**
Correctly formats using the chain token symbol and decimals. This includes `0` which doesn't get a token symbol (I get why, I just disagree with parity's solution of not giving it one)

Fixes #62 

Screenshot 2025-04-29 at 10-51-35 Delia
Screenshot 2025-04-29 at 10-51-42 Delia
Screenshot 2025-04-29 at 10-51-50 Delia

### CODE REVIEW

File: src/GlobalCtx.tsx [hunk 1]
```diff
@@ -1,15 +1,69 @@
...
+    return unit * this.tokenDecimals;
+  }
+
+  planckToUnit(planck: number): number {
+    return planck / this.tokenDecimals;
+  }
+
+  formatUnit(unit: number | bigint): string {
+    // 0 != BigInt(0) hence the ||
+    if (unit === 0 || (typeof unit === "bigint" && BigInt(0) === unit)) {
```
Comment (aidan46) [inline src/GlobalCtx.tsx:45]: I think this does the same but shorter:
```suggestion
    if (unit === 0 || unit === 0n) {
```
The `n` behind the second 0 is indicating that it is a `bigint`

File: src/GlobalCtx.tsx [hunk 2]
```diff
@@ -1,15 +1,69 @@
...
+    return new TokenProperties({
+      // We have a single token, hence the [0]
+      tokenDecimals: systemProperties.tokenDecimals.unwrap()[0].toNumber(),
+      tokenSymbol: systemProperties.tokenSymbol.unwrap()[0].toString(),
+    });
+  }
+
+  /** Converts a given value in the chain's respective UNIT to Plancks (amount denoted by the `tokenDecimals` field). */
+  unitToPlanck(unit: number): number {
+    return unit * this.tokenDecimals;
```
Comment (aidan46) [inline src/GlobalCtx.tsx:36]: This will break when the balance is over 9007 DOT (number.MAX = 9007199254740991 planck = 9007.19 DOT). The `//Alice` account has a higher balance than this when the chain starts. You can calculate the number before and after the decimal similar to [here](https://github.com/eigerco/delia/pull/65/files#diff-608358a6b7f60a47e2636df50d7b135d4967ac1bba83030b9ccfab708cd6fa81R3-R15).

File: src/GlobalCtx.tsx (hunk 1 above)
Comment (jmg-duarte) [reply src/GlobalCtx.tsx:45]: oh nice

**Review by aidan46 — APPROVED** [review]
