### PR TITLE
fix: duration validation

### LINKED ISSUE #84: Duration picker bug
I can't create a deal for a month exactly (days 0)

Image

### PR DESCRIPTION
**Pull request by jmg-duarte**
Fixes #84

### CODE REVIEW

File: src/components/deal-proposal-form/DealProposalForm.tsx [hunk 1]
```diff
@@ -29,10 +29,21 @@ const storageProviderInfoSchema = z.custom<StorageProviderInfo>(isStorageProvide
...
+      .refine(({ months, days }) => !(months === 0 && days === 0), "Deal duration cannot be 0"),
+    // .superRefine(({ months, days }, ctx) => {
+    //   // debugger;
+    //   if (months === 0 && days === 0) {
+    //     ctx.addIssue({
+    //       code: z.ZodIssueCode.custom,
+    //       message: "Deal duration cannot be 0",
+    //     });
+    //   }
+    // }),
```
Comment (Jinxit) [inline src/components/deal-proposal-form/DealProposalForm.tsx:46]: Do we want to keep this commented-out code?

Comment (jmg-duarte) [reply src/components/deal-proposal-form/DealProposalForm.tsx]: ups, nice catch

**Review by aidan46 — APPROVED** [review]

**Review by cernicc — APPROVED** [review]
